name: 'release-version-latest'
description: 'Fetch the latest release version for the current repository'
author: 'peteraritchie'
branding:
  icon: tag
  color: green

outputs:
  version:
    description: 'Latest release version'
    value: ${{ steps.fetch-latest-release-version.outputs.version }}

runs:
  using: 'composite'
  steps:
    - id: fetch-latest-release-version
      run: |
        git fetch --tags
        git fetch --prune --unshallow || true
        export LATEST_RELEASE_VERSION=$(git describe --abbrev=0 --tags || echo "v0.1")
        echo "version=${LATEST_RELEASE_VERSION:1}" >> $GITHUB_OUTPUT
      shell: bash
      