# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET build and integrate

on:
  workflow_call:

jobs:
  build-and-integrate:
    name: build and integrate
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src

    steps:
    - name: version
      id: version
      uses: zwaldowski/match-label-action@v4
      with:
        allowed: major, minor
        default_match: 1.0
    - name: verbose
      run: echo "${{ steps.version.outputs.match }}""
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Test
      run: dotnet test --no-restore --no-build --filter Category!=Integration --verbosity normal --configuration Release -p:CollectCoverage=true -p:CoverletOutput=TestResults/ -p:CoverletOutputFormat=opencover
    - name: Package
      run: dotnet pack --no-build --configuration Release --include-symbols
#
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: nupkg
        # not "src/" prefix, upload-artifact does not support `working-directory`
        path: src/Library/bin/Release/*.nupkg
        if-no-files-found: error
#
