name: ci
run-name: CI run for commit ${{ github.sha }} by ${{ github.actor }}

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/build-integrate.yml

  release:
    needs: ci
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: download version ${{ needs.ci.outputs.version }} artifacts 
      uses: actions/download-artifact@v3
      with:
        name: nupkg-${{ github.sha }}
    - name: get tag name
      id: tag-name
      run: echo "value=v${{ needs.ci.outputs.version }}" >> $GITHUB_OUTPUT
    - name: tag (${{ steps.tag-name.outputs.value }})
      run: |
        git tag ${{ steps.tag-name.outputs.value }}
        git push origin ${{ steps.tag-name.outputs.value }}
    - name: release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "*.nupkg"
        draft: true
        tag: ${{ steps.tag-name.outputs.value }}
        body: release ${{ steps.tag-name.outputs.value }}
