name: ci
run-name: CI run for commit ${{ github.sha }} by ${{ github.actor }}

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/build-integrate.yml

  release:
    needs: ci
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: get tag name
      id: tag-name
      run: echo "value=v${{ needs.ci.outputs.version }}" >> $GITHUB_OUTPUT
    - name: Checkout
      uses: actions/checkout@v3
    - name: tag (${{ steps.tag-name.outputs.value }})
      run: |
        git tag ${{ steps.tag-name.outputs.value }}
        git push origin ${{ steps.tag-name.outputs.value }}
    - name: download version ${{ needs.ci.outputs.version }} artifacts 
      uses: actions/download-artifact@v3
      with:
        name: nupkg-${{ github.sha }}
    - name: publish release ${{ steps.draft-release.outputs.id}}
      id: publish-release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ steps.tag-name.outputs.value }}
        artifacts: "*.nupkg"
        artifactErrorsFailBuild: true
        body: release ${{ steps.tag-name.outputs.value }}
    - name: log ${{ steps.publish-release.outputs.id}}
      run: echo ${{ steps.publish-release.outputs.id}}
    - name: log initial vsixmanifest
      run: cat src/source.extension.vsixmanifest
    - name: vsix version
      uses: Mudlet/xmlstarlet-action@v1.1
      with:
        args: ed -u '/PackageManifest/Metadata/Identity/@Version' -v '${{ needs.ci.outputs.version }}'' src/source.extension.vsixmanifest
    - name: log updated vsixmanifest
      run: cat src/source.extension.vsixmanifest
