name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/build-integrate.yml

  release:
    needs: ci
    runs-on: ubuntu-latest
    steps:
    - name: do something
      run: echo hello world
