name: ci
run-name: CI run for commit ${{ github.sha }} by ${{ github.actor }}

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/build-integrate.yml

  release:
    needs: ci
    runs-on: ubuntu-latest
    steps:
    - name: do something
      run: echo "version ${{ needs.ci.outputs.version }} built."
    - uses: actions/download-artifact@v3
      with:
        name: nupkg-${{ github.sha }}